export const QUERY_KEY_POKEMON_NAME = 'POKEMON_';
export const QUERY_KEY_POKEMON_ABILITY = 'POKEMON_ABILITY';
export const QUERY_KEY_POKEMON_LIST_HOME = 'POKEMON-LIST-HOME';

export const POKEMON_DEFAULT_LANGUAGE = 'en';
export const NETWORK_THROTTLING_DELAY = 4_000;
